name: 'vibe_data_platform'
version: '1.0.0'
config-version: 2

profile: 'vibe_duckdb'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  vibe_data_platform:
    staging:
      +materialized: view
    marts:
      +materialized: table
